### ISSUE TITLE
[Feature] possible transparency support?

### ISSUE THREAD

**Issue by Frontear** [AdaelynXIV/RoundedDark#1]
Noticing the theme has the background blue (im guessing due to the spacing and blurple color). Perhaps it could be possible to prod around and achieve transparency support, making the blue background transparent instead?

**Comment by AdaelynXIV** [comment]
Thanks for your suggestion! 
I've implemented this in [Release v1.2.1](https://github.com/AdaelynXIV/RoundedDark/releases/tag/V1.2.1).

**Comment by AdaelynXIV** [comment]
Apologies! I misunderstood your suggestion, I'll take a look into it.

**Comment by Frontear** [comment]
As a little mention, channels tabs has an issue where the colors aren't correctly applied between the tabs. You can see it doesn't respect custom-background colors.

![image](https://user-images.githubusercontent.com/31909298/208548450-43b5225a-f51e-470e-9b25-b40b9b0cf923.png)

**Comment by AdaelynXIV** [comment]
Thanks for notifying me! I pushed out a fix for that issue.
