### ISSUE TITLE
[Suggestion] Moving the window buttons (min, max, close), to a different spot when ChannelTabs support is enabled

### ISSUE THREAD

**Issue by Frontear** [AdaelynXIV/RoundedDark#2]
Apologies for bombarding the repo haha, I really like this theme and have a lot of suggestions. 

![image](https://user-images.githubusercontent.com/31909298/208551741-6c5c2b66-7b54-42f1-9223-dbb487fc38e5.png)

I'm noticing with the channel tabs the close, minimize, and maximize buttons are placed in a rather strange place. It overlaps a lot with muscle memory for the X button that would be shown for threads, or popups. I'm not sure where an alternative location would be, but I think where it is looks a bit odd and would be inconvenient for the user, who expects it near the tip-top of the screen, on the right hand side

**Comment by AdaelynXIV** [comment]
> Apologies for bombarding the repo haha, I really like this theme and have a lot of suggestions.
No worries at all! Appreciate the feedback.

---

I'll have a look into a possible solution, moving the X button toolbar upward could be one, it's a little tricky due to the toolbar not respecting ChannelTabs size/position.

**Comment by AdaelynXIV** [comment]
Fixed this in the most recent commit, should hopefully be a more permanent solution.
