### ISSUE TITLE
[Bug] VC Buttons have differing shapes (not all respecting radius)

### ISSUE THREAD

**Issue by Frontear** [AdaelynXIV/RoundedDark#4]
Seems fairly trivial, these buttons are not all respecting the radius variable. Not high priority since it really isn't all that noticeable in most scenarios
![image](https://user-images.githubusercontent.com/31909298/209067596-3e3e1041-d3cd-470e-84e1-c797f633e7c5.png)

**Comment by AdaelynXIV** [comment]
Pushed out a fix!
