### ISSUE TITLE
[Suggestion] Show the server icons in the folder

### ISSUE THREAD

**Issue by Dohvakin** [AdaelynXIV/RoundedDark#5]
Hi,

I would like to suggest that like the vanilla discord we should be able to see the servers in the folder. I usually use the server icons in the folder to identify if I need to open that folder or not to get to the specific discord server.

![image](https://user-images.githubusercontent.com/26587446/209435523-ca8f3b74-9ee8-49c4-9642-93d66279f60c.png)

It's much easier to know what folder contains what folder this way.

**Comment by AdaelynXIV** [comment]
You can change this in the Theme Settings.

User Settings > Themes > Edit (on RoundedDark).

Inside the file, remove the "Coloured Folder Icons" part at the bottom:
`/* Coloured Folder Icons by CapnKitten (Gibbu#1211 edit)*/
/* If you wish to remove the Folder Icons; or if it breaks one of your plug-ins, remove everything under here: */
.closedFolderIconWrapper-3tRb2d {
    display: none;
}
.folderIconWrapper-1oRIZr:not([style=""])::before {
    position: absolute;
    content: "";
    width: 18px;
    height: 18px;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    margin: auto;
    background-color: inherit;
    -webkit-mask: url(https://capnkitten.github.io/BetterDiscord/Themes/Material-Discord/files/icons/solid/folder.svg) no-repeat;
    mask: url(https://capnkitten.github.io/BetterDiscord/Themes/Material-Discord/files/icons/solid/folder.svg) no-repeat;
    transform: scale(1.3335);
    filter: brightness(1.5) saturate(1.5);
}`

**Comment by Dohvakin** [comment]
I've removed that code and still don't see the server icons; I don't know what I am missing 
![image](https://user-images.githubusercontent.com/26587446/209436069-b6b23b39-fce7-4ebe-bf1a-902bbdda2183.png)

**Comment by AdaelynXIV** [comment]
Apologies, pushed a quick fix, should become visible shortly (may need to restart for it to appear).

**Comment by Dohvakin** [comment]
yup working now thanks!!
